{% set name = "hkdf" %}
{% set version = "0.0.3" %}
{% set sha256 = "622a31c634bc185581530a4b44ffb731ed208acf4614f9c795bdd70e77991dca" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 3
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - nose
    - python {{ python_min }}
  commands:
    - nosetests
about:
  home: https://github.com/casebeer/python-hkdf
  license: BSD-2
  license_family: BSD
#  license_file: LICENSE
  summary: 'This module implements the HMAC Key Derivation function,
  defined at http://tools.ietf.org/html/draft-krawczyk-hkdf-01 '
  description: |
    This module implements the HMAC Key Derivation function, defined at
    http://tools.ietf.org/html/draft-krawczyk-hkdf-01
    There are two interfaces: a functional interface, with separate extract
    and expand functions as defined in the draft RFC, and a wrapper class for
    these functions.
  doc_url: https://github.com/casebeer/python-hkdf
  dev_url: https://github.com/casebeer/python-hkdf

extra:
  recipe-maintainers:
    - CJ-Wright
