travis:
  secure:
    BINSTAR_TOKEN: hq6pW1AOnlArIjhOvkbg4biEOdd6es04QeFWUhZO7Euhh0aj2JKrZWEMm9dZxWGjFVedYvgMiuRmTHAmDbaDB61OPO+L7unBwA6VDV9Qm/+awn4GtnluG1Bo9SmAxkeys1NdfRBo7jaIw7rW4khr5XcmHQ8DKNsTQhYEUAjCd3OXCkFlF/4qGiOume+OPASAc+uVJn5Nqio5VMO9YEPSL1rpgvYWKGLMW7Ehhaa/2o2KlDsvizdGjB7XjGhw2XOTAivnM4AeD2nJvtfhHlcnh1stqHG00XHaU38Mlie3m+v1xKABb7ebKnYMHyz2bxFLwkun0Y0NeAukHdHYEAVUBt+4+gUm8oAsOZTM4sYc/PhCduQExoFMUJTp5vZR9dmpmWwWC/413k3p26ZcRTeZe1cO3KR5BTyH/sYxyr14ox1ZmDZQ0OktlImRi0lfj+A2pozGyg0U4v6ew4rIj4cZRTUGFmX1rbP6yUuyFFwenjX8bCx2w4xwGDCTMHmXhqHXchoUUqu4hrbnr0bNmpH/uL4aiOyULNbIxQUYfJFO0JqwoUBixw5AmIMNCQpRIfX1YanVBIlUbpGubQyb/QuB60vRF4sr+/O9G7IQ4qCBs5YYtU4f0q6/vOwbCS6ADvxQec6v8IgKdhZlVBob2+xD5FWWshcM4ndTsMF0Z9KwWw4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
