travis:
  secure:
    BINSTAR_TOKEN: bUcsvpV7ClgsGquKQvWjNhF8fWlQiwZoulqnjMEuo76VmIvj2i3ppfU6EO3LqstD8UTKdpFnv8DbGD3qh8y2JVY2Pj9aWcoGp5cOcxgyTuUgbQjGwDXSoEXytlstdxiNGraBvfdwNJI+s1keBK3TQUXflrqX/ADDACbPww06UquuNwDZsuCebBcEiaseCHCMOncNOwiWqlG95tw6v3PF0eYCCLeZQi1xZ8qZod8wZBSiT92IiYwvfcYXwHqHXjq2l/Ng9NDgJI5uD1+r9MWpRpmG+U3wuuWhAlf8pmz8jcUqaYPfECj6RCGOjFSVBuq5cKSV2Xnx6f8W93lL85cRW71hDUtBHhVBUqV7K3AX+MEpKA3plrbJAUinURDOk6dcRYYdwvoD1pKf1VV3JormGQh+SXP/eBHrgr2VtlpvJEXIi5aZ3q5o6oxLOSJzLRFZpl7Y1LxJn/qjUi21Hn2cSJdjRRfNXME22eKQu51hWEw+MeFrqa+jYP06K68ZWFt4zjGIVRKw2oikPjRw6T9ktGqIEHhdneJ7RT4jeUtunJW5nj5TuPyLfZYSOB5pTHhtGMQBeYsyc1lmf2GzgYmxElRi/8OWTtKUoiljBMyrh5IPubKz55IQ77W5abx9PAiBbAAuHqgK3qc80iaLw8YafjE8SNM8xCpdnGrOh0sGy6s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
